image: ghcr.io/jethome-homeassistant/{arch}-base-python
build_from:
  aarch64: "ghcr.io/jethome-homeassistant/aarch64-base:"
  amd64: "ghcr.io/jethome-homeassistant/amd64-base:"
cosign:
  base_identity: https://github.com/jethome-homeassistant/docker-base/.*
  identity: https://github.com/jethome-homeassistant/docker-base/.*
args:
  PYTHON_VERSION: "3.14.2"
  PIP_VERSION: "25.3"
  CERT_IDENTITY: hugo@python.org
  CERT_OIDC_ISSUER: https://github.com/login/oauth
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/jethome-homeassistant/docker-base
